# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squares', '0002_auto_20170420_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_bingoed',
            field=models.BooleanField(default=False),
        ),
    ]
